### PR TITLE
Feature for passing parameters into navigation-partial.

### PR DESCRIPTION
**Pull request by Zyqsempai**
Finished feature for passing parameters into navigation helper partial view model. new branch with @weierophinney 's idea realization.

### CODE REVIEW

**Comment by Zyqsempai** [comment]
I think that we can close this one <a href="https://github.com/zendframework/zend-view/pull/7">#7</a> , to mach conflicts on that branch.

**Comment by Martin-P** [comment]
Can you please undo all cosmetic changes, like:
- ending comments with a dot `.`
- removal of spaces when concatenating strings
- removal of empty lines
- adding empty lines before `@return` annotations
- etc.

The correct coding standard is the way @weierophinney wrote it: https://github.com/weierophinney/zend-view/commit/80912976f00a90ea1d7f84984edd74e424e07d13

**Comment by Zyqsempai** [comment]
I skipped my code through php-cs-fixer and i thought that it will fix all those cosmetic issues.

**Comment by Maks3w** [comment]
Did you execute php-cs-fixer with the provided .php_cs file?

As @mwillbanks said please undo all that stuff

**Comment by weierophinney** [comment]
Merged to develop for release with 2.6.0.

**Pull request closed without merging**
